# fly.toml app configuration file generated for gogolook-test on 2024-01-16T18:58:01+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "gogolook-test"
primary_region = "nrt"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
